<OPTION value=Afghanistan>Afghanistan</OPTION>
<OPTION value=Albania>Albania</OPTION>
<OPTION value=Algeria>Algeria</OPTION>
<OPTION value="American Samoa">American Samoa</OPTION>
<OPTION value=Andora>Andora</OPTION>
<OPTION value=Angola>Angola</OPTION>
<OPTION value=Anguilla>Anguilla</OPTION>
<OPTION value=Antarctica>Antarctica</OPTION>
<OPTION value="Antigua and Barbuda">Antigua and Barbuda</OPTION>
<OPTION value=Argentina>Argentina</OPTION>
<OPTION value=Armenia>Armenia</OPTION>
<OPTION value=Aruba>Aruba</OPTION>
<OPTION value=Australia>Australia</OPTION>
<OPTION value=Austria>Austria</OPTION>
<OPTION value=Azerbaijan>Azerbaijan</OPTION>
<OPTION value=Bahamas>Bahamas</OPTION>
<OPTION value=Bahrein>Bahrein</OPTION>
<OPTION value=Bangladesh>Bangladesh</OPTION>
<OPTION value=Barbados>Barbados</OPTION>
<OPTION value=Belarus>Belarus</OPTION>
<OPTION value=Belgium>Belgium</OPTION>
<OPTION value=Belize>Belize</OPTION>
<OPTION value=Benin>Benin</OPTION>
<OPTION value=Bermuda>Bermuda</OPTION>
<OPTION value=Bhutan>Bhutan</OPTION>
<OPTION value=Bolivia>Bolivia</OPTION>
<OPTION value=Bosnia-Herzegovina>Bosnia-Herzegovina</OPTION>
<OPTION value=Botswana>Botswana</OPTION>
<OPTION value="Bouvet Island">Bouvet Island</OPTION>
<OPTION value=Brazil>Brazil</OPTION>
<OPTION value="British Indian Ocean Territory">British Indian Ocean Territory</OPTION>
<OPTION value="British Virgin Island">British Virgin Island</OPTION>
<OPTION value="Brunei Darussalam">Brunei Darussalam</OPTION>
<OPTION value=Bulgaria>Bulgaria</OPTION>
<OPTION value="Burkina Faso">Burkina Faso</OPTION>
<OPTION value=Burundi>Burundi</OPTION>
<OPTION value=Cameroon>Cameroon</OPTION>
<OPTION value=Canada>Canada</OPTION>
<OPTION value="Cape Verde">Cape Verde</OPTION>
<OPTION value="Cayman Islands">Cayman Islands</OPTION>
<OPTION value="Central African Republic">Central African Republic</OPTION>
<OPTION value=Chad>Chad</OPTION>
<OPTION value=Chile>Chile</OPTION>
<OPTION value=China>China</OPTION>
<OPTION value="Christmas Island">Christmas Island</OPTION>
<OPTION value="Cocos Islands">Cocos Islands</OPTION>
<OPTION value=Colombia>Colombia</OPTION>
<OPTION value=Comoros>Comoros</OPTION>
<OPTION value=Congo>Congo</OPTION>
<OPTION value="Cook Islands">Cook Islands</OPTION>
<OPTION value="Costa Rica">Costa Rica</OPTION>
<OPTION value="Cote dIvoire">Cote dIvoire</OPTION>
<OPTION value=Croatia>Croatia</OPTION>
<OPTION value=Cuba>Cuba</OPTION>
<OPTION value=Cyprus>Cyprus</OPTION>
<OPTION value="Czech Republic">Czech Republic</OPTION>
<OPTION value="Democratic Kampuchea">Democratic Kampuchea</OPTION>
<OPTION value=Denmark>Denmark</OPTION>
<OPTION value=Djibouti>Djibouti</OPTION>
<OPTION value=Dominica>Dominica</OPTION>
<OPTION value="Dominican Republic">Dominican Republic</OPTION>
<OPTION value="East Timor">East Timor</OPTION>
<OPTION value=Ecuador>Ecuador</OPTION>
<OPTION value=Egypt>Egypt</OPTION>
<OPTION value="El Salvador">El Salvador</OPTION>
<OPTION value="Equatorial Guinea">Equatorial Guinea</OPTION>
<OPTION value=Estonia>Estonia</OPTION>
<OPTION value=Ethiopia>Ethiopia</OPTION>
<OPTION value="Faeroe Islands">Faeroe Islands</OPTION>
<OPTION value="Falkland Islands">Falkland Islands</OPTION>
<OPTION value="Fiji Islands">Fiji Islands</OPTION>
<OPTION value=Finland>Finland</OPTION>
<OPTION value=France>France</OPTION>
<OPTION value="French Guiana">French Guiana</OPTION>
<OPTION value="French Polynesia">French Polynesia</OPTION>
<OPTION value=Gabon>Gabon</OPTION>
<OPTION value=Gambia>Gambia</OPTION>
<OPTION value=Georgia>Georgia</OPTION>
<OPTION value=Germany>Germany</OPTION>
<OPTION value=Ghana>Ghana</OPTION>
<OPTION value=Gibraltar>Gibraltar</OPTION>
<OPTION value=Greece>Greece</OPTION>
<OPTION value=Greenland>Greenland</OPTION>
<OPTION value=Grenada>Grenada</OPTION>
<OPTION value=Guadeloupe>Guadeloupe</OPTION>
<OPTION value=Guam>Guam</OPTION>
<OPTION value=Guatemala>Guatemala</OPTION>
<OPTION value=Guinea>Guinea</OPTION>
<OPTION value=Guinea-Bissau>Guinea-Bissau</OPTION>
<OPTION value=Guyana>Guyana</OPTION>
<OPTION value=Haiti>Haiti</OPTION>
<OPTION value="Heard and McDonald Islands">Heard and McDonald Islands</OPTION>
<OPTION value=Honduras>Honduras</OPTION>
<OPTION value=Hong Kong>Hong Kong</OPTION>
<OPTION value=Hungary>Hungary</OPTION>
<OPTION value=Iceland>Iceland</OPTION>
<OPTION value=India>India</OPTION>
<OPTION value=Indonesia>Indonesia</OPTION>
<OPTION value=Iran>Iran</OPTION>
<OPTION value=Iraq>Iraq</OPTION>
<OPTION value=Ireland>Ireland</OPTION>
<OPTION value=Israel>Israel</OPTION>
<OPTION value=Italy>Italy</OPTION>
<OPTION value=Jamaica>Jamaica</OPTION>
<OPTION value=Japan>Japan</OPTION>
<OPTION value=Jordan>Jordan</OPTION>
<OPTION value=Kazakhstan>Kazakhstan</OPTION>
<OPTION value=Kenya>Kenya</OPTION>
<OPTION value=Kiribati>Kiribati</OPTION>
<OPTION value=Kuwait>Kuwait</OPTION>
<OPTION value=Kyrgyzsta>Kyrgyzstan</OPTION>
<OPTION value=Laos>Laos</OPTION>
<OPTION value=Latvia>Latvia</OPTION>
<OPTION value=Lebanon>Lebanon</OPTION>
<OPTION value=Lesotho>Lesotho</OPTION>
<OPTION value=Liberia>Liberia</OPTION>
<OPTION value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</OPTION>
<OPTION value=Liechtenstein>Liechtenstein</OPTION>
<OPTION value=Lithuania>Lithuania</OPTION>
<OPTION value=Luxembourg>Luxembourg</OPTION>
<OPTION value=Macau>Macau</OPTION>
<OPTION value=Macedonia>Macedonia</OPTION>
<OPTION value=Madagascar>Madagascar</OPTION>
<OPTION value=Malawi>Malawi</OPTION>
<OPTION value=Malaysia>Malaysia</OPTION>
<OPTION value=Maldives>Maldives</OPTION>
<OPTION value=Mali>Mali</OPTION>
<OPTION value=Malta>Malta</OPTION>
<OPTION value=Martinique>Martinique</OPTION>
<OPTION value=Mauritania>Mauritania</OPTION>
<OPTION value=Mauritius>Mauritius</OPTION>
<OPTION value=Mexico>Mexico</OPTION>
<OPTION value="Midway Islands">Midway Islands</OPTION>
<OPTION value=Monaco>Monaco</OPTION>
<OPTION value=Mongolia>Mongolia</OPTION>
<OPTION value=Montserrat>Montserrat</OPTION>
<OPTION value=Morocco>Morocco</OPTION>
<OPTION value=Mozambique>Mozambique</OPTION>
<OPTION value=Namibia>Namibia</OPTION>
<OPTION value=Nauru>Nauru</OPTION>
<OPTION value=Nepal>Nepal</OPTION>
<OPTION value=Netherlands>Netherlands</OPTION>
<OPTION value="Netherlands Antilles">Netherlands Antilles</OPTION>
<OPTION value=New_Caladonia>New Caladonia</OPTION>
<OPTION value=New_Zealand>New Zealand</OPTION>
<OPTION value=Nicaragua>Nicaragua</OPTION>
<OPTION value=Niger>Niger</OPTION>
<OPTION value=Nigeria>Nigeria</OPTION>
<OPTION value=Niue>Niue</OPTION>
<OPTION value="Norfolk Island">Norfolk Island</OPTION>
<OPTION value="Northern Mariana Islands">Northern Mariana Islands</OPTION>
<OPTION value=Norway>Norway</OPTION>
<OPTION value=Oman>Oman</OPTION>
<OPTION value=Pakistan>Pakistan</OPTION>
<OPTION value=Panama>Panama</OPTION>
<OPTION value="Papua New Guinea">Papua New Guinea</OPTION>
<OPTION value=Paraguay>Paraguay</OPTION>
<OPTION value=Peru>Peru</OPTION>
<OPTION value=Philippines>Philippines</OPTION>
<OPTION value=Pitcairn>Pitcairn</OPTION>
<OPTION value=Poland>Poland</OPTION>
<OPTION value=Portugal>Portugal</OPTION>
<OPTION value="Puerto Rico">Puerto Rico</OPTION>
<OPTION value=Qatar>Qatar</OPTION>
<OPTION value="Republic of Moldova">Republic of Moldova</OPTION>
<OPTION value=Reunion>Reunion</OPTION>
<OPTION value=Romania>Romania</OPTION>
<OPTION value="Russian Federation">Russian Federation</OPTION>
<OPTION value=Rwanda>Rwanda</OPTION>
<OPTION value=Samoa>Samoa</OPTION>
<OPTION value="San Marino">San Marino</OPTION>
<OPTION value="Sao Tome and Principe">Sao Tome and Principe</OPTION>
<OPTION value="Saudi Arabia">Saudi Arabia</OPTION>
<OPTION value=Senegal>Senegal</OPTION>
<OPTION value=Seychelles>Seychelles</OPTION>
<OPTION value="Sierra Leone">Sierra Leone</OPTION>
<OPTION value=Singapore>Singapore</OPTION>
<OPTION value="Slovak Republic">Slovak Republic</OPTION>
<OPTION value=Slovenia>Slovenia</OPTION>
<OPTION value="Solomon Islands">Solomon Islands</OPTION>
<OPTION value=Somalia>Somalia</OPTION>
<OPTION value="South Africa">South Africa</OPTION>
<OPTION value="South Korea">South Korea</OPTION>
<OPTION value=Spain>Spain</OPTION>
<OPTION value="Sri Lanka">Sri Lanka</OPTION>
<OPTION value="St Vincent and the Grenadines">St Vincent and the Grenadines</OPTION>
<OPTION value="St Helena">St Helena</OPTION>
<OPTION value="St Kitts and Nevis">St Kitts and Nevis</OPTION>
<OPTION value="St Lucia">St Lucia</OPTION>
<OPTION value="St Pierre and Miquelon">St Pierre and Miquelon</OPTION>
<OPTION value=Sudan>Sudan</OPTION>
<OPTION value=Suriname>Suriname</OPTION>
<OPTION value="Svalbard & Jan Mayen Islands">Svalbard & Jan Mayen Islands</OPTION>
<OPTION value=Swaziland>Swaziland</OPTION>
<OPTION value=Sweden>Sweden</OPTION>
<OPTION value=Switzerland>Switzerland</OPTION>
<OPTION value=Syria>Syria</OPTION>
<OPTION value=Taiwan>Taiwan</OPTION>
<OPTION value=Tajikistan>Tajikistan</OPTION>
<OPTION value=Tanzania>Tanzania</OPTION>
<OPTION value=Thailand>Thailand</OPTION>
<OPTION value=Tokelau>Togo</OPTION>
<OPTION value=Tokelau>Tokelau</OPTION>
<OPTION value=Tonga>Tonga</OPTION>
<OPTION value="Trinidad and Tobago">Trinidad and Tobago</OPTION>
<OPTION value=Tunesia>Tunesia</OPTION>
<OPTION value=Turkey>Turkey</OPTION>
<OPTION value=Turkmenistan>Turkmenistan</OPTION>
<OPTION value="Turks and Caicos Islands">Turks and Caicos Islands</OPTION>
<OPTION value=Tuvalu>Tuvalu</OPTION>
<OPTION value=U.S.A>U.S.A</OPTION>
<OPTION value="US Virgin Islands">US Virgin Islands</OPTION>
<OPTION value=Uganda>Uganda</OPTION>
<OPTION value=Ukraine>Ukraine</OPTION>
<OPTION value="United Arab Emirates">United Arab Emirates</OPTION>
<OPTION value="United Kingdom">United Kingdom</OPTION>
<OPTION value=Uruguay>Uruguay</OPTION>
<OPTION value=Uzbekistan>Uzbekistan</OPTION>
<OPTION value=Vanuatu>Vanuatu</OPTION>
<OPTION value="Vatican City">Vatican City</OPTION>
<OPTION value=Venezuela>Venezuela</OPTION>
<OPTION value=Vietnam>Vietnam</OPTION>
<OPTION value="Wallis and Fortuna Islands">Wallis and Fortuna Islands</OPTION>
<OPTION value=Yemen>Yemen</OPTION>
<OPTION value=Yugoslavia>Yugoslavia</OPTION>
<OPTION value=Zambia>Zambia</OPTION>
<OPTION value=Zimbabwe>Zimbabwe</OPTION>