<?php

use Proxy\Api\Api;

include '../../lib/functions.php';
include '../../config.php';

include_once 'simbrief.apiv1.php';
Api::__constructStatic();
session_start();
validateSession();

$date = date("Y-m-d H:i", strtotime("+30 minutes"));
$hasBooking = false;
$aircraft = "";
$aircraftReg = "";
$origin = "";
$destination = "";
$flightNumber = "";
$route = "";
$pax = "";
$cargo = "";
$settings = null;
$limitDepatureLocation = false;
$res = Api::sendSync('GET', 'v1/airline', null);
if ($res->getStatusCode() == 200) {
    $settings = json_decode($res->getBody(), false);
    $limitDepatureLocation = $settings->limitDepartureLocation;
}
$currentLocation = "";
if ($limitDepatureLocation) {
    $res = Api::sendAsync('GET', 'v1/pilot/location', null);
    if ($res->getStatusCode() == 200) {
        $response = json_decode($res->getBody());
        $currentLocation = $response->location;
        if ($currentLocation != '') $origin = $currentLocation;
    }
}
$res = Api::sendAsync('GET', 'v1/bid/' . $_SESSION['pilotid'], null);
if ($res->getStatusCode() == 200) {
    $bid = json_decode($res->getBody());
    $hasBooking = true;
    $aircraft = $bid->aircraft;
    $aircraftReg = $bid->aircraftReg;
    $origin = $bid->departureIcao;
    $destination = $bid->arrivalIcao;
    $flightNumber = $bid->flightNumber;
    $route = $bid->route;
    $pax = $bid->totalPax;
    $cargo = $bid->cargo;
}
?>
<?php
$MetaPageTitle = "";
$MetaPageDescription = "";
$MetaPageKeywords = "";
?>
<?php include '../../includes/header.php'; ?>
<section id="content" class="cp section offset-header">
    <div class="container">
        <?php if (!empty($status)) { ?>
            <div class="row">
                <?php if ($status == "error") { ?>
                    <div class="alert alert-danger" role="alert">
                        <p><i class="fa fa-warning" aria-hidden="true"></i> An error occurred when filling the manual PIREP.
                            Please try again later.</p>
                    </div>
                <?php } ?>
                <?php if ($status == "required_fields") { ?>
                    <div class="alert alert-danger" role="alert">
                        <p> <i class="fa fa-warning" aria-hidden="true"></i> Please check all fields have been completed
                            correctly.</p>
                    </div>
                <?php } ?>
            </div>
        <?php } ?>
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">SimBrief Dispatch</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <p><i class="fa fa-info" aria-hidden="true"></i> Leave fields that are not required blank to
                                be
                                auto-generated by SimBrief.</p>
                        </div>
                        <form method="post" class="form" id="sbapiform">
                            <div class="col-md-6">
                                <h3>Flight Plan</h3>
                                <div class="form-group">
                                    <label>Aircraft ICAO*:</label>
                                    <input name="type" type="text" id="type" class="form-control"
                                        style="text-transform:uppercase" required value="<?php echo $aircraft; ?>" />
                                </div>
                                <div class="form-group">
                                    <label>Aircraft Reg:</label>
                                    <input name="reg" type="text" id="reg" value="<?php echo $aircraftReg; ?>"
                                        style="text-transform:uppercase" maxlength="15" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label>Flight Number*:</label>
                                    <input name="fltnum" type="text" id="fltnum" style="text-transform:uppercase"
                                        value="<?php echo empty($flightNumber) ? simbrief_airline : $flightNumber; ?>"
                                        maxlength="10" class="form-control"
                                        <?php echo !empty($flightNumber) ? "readonly" : "" ?> />
                                </div>
                                <div class="form-group">
                                    <label>Origin*:</label>
                                    <input name="orig" type="text" id="orig" maxlength="4" class="form-control"
                                        style="text-transform:uppercase" required value="<?php echo $origin; ?>"
                                        <?php echo !empty($origin) ? "readonly" : "" ?> />
                                </div>
                                <div class="form-group">
                                    <label>Destination*:</label>
                                    <input name="dest" type="text" id="dest" maxlength="4" class="form-control"
                                        style="text-transform:uppercase" required value="<?php echo $destination; ?>"
                                        <?php echo !empty($destination) ? "readonly" : "" ?> />
                                </div>
                                <div class="form-group">
                                    <label>PAX:</label>
                                    <input name="pax" type="text" id="pax" maxlength="25" class="form-control"
                                        value="<?php echo $pax; ?>" />
                                </div>
                                <div class="form-group">
                                    <label>Cargo (<?php echo cargo_weight_display == 1 ? 'lb' : 'kg' ?>):</label>
                                    <input name="cargo" type="text" id="cargo" maxlength="25" class="form-control"
                                        style="text-transform:uppercase"
                                        value="<?php echo !empty($cargo) ? str_replace('kg', '', str_replace('lb', '', getCargoDisplayValue($cargo))) : ""; ?>" />
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Route:</label>
                                    <textarea name="route" cols="50" rows="5" id="route" class="form-control"
                                        style="text-transform:uppercase"><?php echo $route; ?></textarea>
                                </div>
                                <div class="form-group">
                                    <label>Reserve Fuel:</label>
                                    <select name="resvrule" required>
                                        <option value="auto">AUTO</option>
                                        <option value="0">0 MIN</option>
                                        <option value="15">15 MIN</option>
                                        <option value="30">30 MIN</option>
                                        <option value="45" selected>45 MIN</option>
                                        <option value="60">60 MIN</option>
                                        <option value="75">75 MIN</option>
                                        <option value="90">90 MIN</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Departure Time:</label>
                                    <div class="row">
                                        <div class="col-md-6">
                                            Hours
                                            <select name="deph" id="deph" class="form-control">
                                                <option value="01">01</option>
                                                <option value="02">02</option>
                                                <option value="03">03</option>
                                                <option value="04">04</option>
                                                <option value="05">05</option>
                                                <option value="06">06</option>
                                                <option value="07">07</option>
                                                <option value="08">08</option>
                                                <option value="09">09</option>
                                                <option value="10">10</option>
                                                <option value="11">11</option>
                                                <option value="12">12</option>
                                                <option value="13">13</option>
                                                <option value="14">14</option>
                                                <option value="15">15</option>
                                                <option value="16">16</option>
                                                <option value="17">17</option>
                                                <option value="18">18</option>
                                                <option value="19">19</option>
                                                <option value="20">20</option>
                                                <option value="21">21</option>
                                                <option value="22">22</option>
                                                <option value="23">23</option>
                                                <option value="00">00</option>
                                            </select>
                                        </div>
                                        <div class="col-md-6">
                                            Minutes
                                            <select name="depm" id="depm" class="form-control">
                                                <option value="00">00</option>
                                                <option value="01">01</option>
                                                <option value="02">02</option>
                                                <option value="03">03</option>
                                                <option value="04">04</option>
                                                <option value="05">05</option>
                                                <option value="06">06</option>
                                                <option value="07">07</option>
                                                <option value="08">08</option>
                                                <option value="09">09</option>
                                                <option value="10">10</option>
                                                <option value="11">11</option>
                                                <option value="12">12</option>
                                                <option value="13">13</option>
                                                <option value="14">14</option>
                                                <option value="15">15</option>
                                                <option value="16">16</option>
                                                <option value="17">17</option>
                                                <option value="18">18</option>
                                                <option value="19">19</option>
                                                <option value="20">20</option>
                                                <option value="21">21</option>
                                                <option value="22">22</option>
                                                <option value="23">23</option>
                                                <option value="24">24</option>
                                                <option value="25">25</option>
                                                <option value="26">26</option>
                                                <option value="27">27</option>
                                                <option value="28">28</option>
                                                <option value="29">29</option>
                                                <option value="30">30</option>
                                                <option value="31">31</option>
                                                <option value="32">32</option>
                                                <option value="33">33</option>
                                                <option value="34">34</option>
                                                <option value="35">35</option>
                                                <option value="36">36</option>
                                                <option value="37">37</option>
                                                <option value="38">38</option>
                                                <option value="39">39</option>
                                                <option value="40">40</option>
                                                <option value="41">41</option>
                                                <option value="42">42</option>
                                                <option value="43">43</option>
                                                <option value="44">44</option>
                                                <option value="45">45</option>
                                                <option value="46">46</option>
                                                <option value="47">47</option>
                                                <option value="48">48</option>
                                                <option value="49">49</option>
                                                <option value="50">50</option>
                                                <option value="51">51</option>
                                                <option value="52">52</option>
                                                <option value="53">53</option>
                                                <option value="54">54</option>
                                                <option value="55">55</option>
                                                <option value="56">56</option>
                                                <option value="57">57</option>
                                                <option value="58">58</option>
                                                <option value="59">59</option>
                                            </select>
                                        </div>
                                    </div>
                                    <p class="help-block">Time is UTC</p>
                                </div>
                                <h3>Overrides</h3>
                                <div class="form-group">
                                    <label>Runways:</label>
                                    <div class="row">
                                        <div class="col-md-6">
                                            Departure
                                            <input type="text" name="origrwy" class="form-control" maxlength="3"
                                                style="text-transform:uppercase" />
                                        </div>
                                        <div class="col-md-6">
                                            Arrival
                                            <input type="text" name="destrwy" class="form-control" maxlength="3"
                                                style="text-transform:uppercase" />
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div>
                                        <input name="cpt" type="hidden" value="<?php echo $_SESSION['name']; ?>" />
                                        <input type="hidden" name="airline" value="<?php echo simbrief_airline; ?>">
                                        <input type="hidden" name="addedfuel"
                                            value="<?php echo simbrief_extra_fuel_minutes; ?>">
                                        <input type="hidden" name="addedfuel_units" value="min">
                                        <input type="hidden" name="civalue" value="<?php echo simbrief_cost_index; ?>">
                                        <input type="hidden" name="maps" value="detailed">
                                        <input type="hidden" name="firnot" value="1">
                                        <input type="hidden" name="notams" value="1">
                                        <input type="hidden" name="tlr" value="1">
                                        <input type="hidden" name="navlog" value="1">
                                        <input type="hidden" name="etops" value="1">
                                        <input type="hidden" name="cruise" value="CI" />
                                        <input type="hidden" name="units"
                                            value="<?php echo fuel_weight_display == 1 ? 'LBS' : 'KGS' ?>">
                                        <input type="hidden" name="stepclimbs" value="1">
                                        <input type="hidden" name="planformat"
                                            value="<?php echo simbrief_flight_plan_format; ?>">
                                        <input type="hidden" name="acdata"
                                            value="{'extrarmk':'OPR\/<?php echo simbrief_custom_fp_remarks; ?>'}">
                                        <input name="btnDispatch" type="submit" id="btnDispatch" value="Dispatch Flight"
                                            class="btn btn-success">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"><strong>Dispatch Error<strong></h4>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="btnCloseCancel" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>
<?php include '../../includes/footer.php'; ?>
<script type="text/javascript" src="<?php echo website_base_url; ?>assets/js/simbrief.apiv1.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        var limitDepartureLocation = <?php echo $limitDepatureLocation ? 'true' : 'false'; ?>;
        var currentLocation = '<?php echo $currentLocation ?? ''; ?>';
        var hour = '<?php echo (new Datetime($date))->format('H'); ?>';
        var min = '<?php echo (new Datetime($date))->format('i'); ?>';

        $("#deph").val(hour);
        $("#depm").val(min);

        $("#btnDispatch").on('click', function(event) {
            if ($("#sbapiform")[0].checkValidity()) {
                event.preventDefault();
                Loader.start();

                if (limitDepartureLocation && currentLocation != '') {
                    if ($("#orig").val().toUpperCase() != currentLocation) {
                        Loader.stop();
                        $("#errorModal").modal("show");
                        $(".modal-body").html(
                            "<p>You must start your flight from your current location (" +
                            currentLocation + ").</p>");
                        return;
                    }
                }

                var $form = $("#sbapiform");
                var $inputs = $form.find("input[type='text'], input[type='hidden']");
                var serializedData = $form.serialize();
                request = $.ajax({
                    url: "pilot_ac_rank_check.php",
                    type: "POST",
                    data: serializedData
                });
                request.done(function(response, textStatus, jqXHR) {
                    var r = response;
                    if (r == "true") {
                        simbriefsubmit('output.php');
                    } else {
                        Loader.stop();
                        $("#errorModal").modal("show");
                        $(".modal-body").html(
                            "<p>You are not authorised to fly this aircraft.</p>");
                    }
                });
                request.fail(function(jqXHR, textStatus, errorThrown) {
                    $(".jump-error").show();
                    console.error(
                        "The following error occurred: " +
                        textStatus, errorThrown
                    );
                });
            }
        });
    });
</script>